DROP TABLE ACCOUNTING_ENTRIES
GO
DROP TABLE ACCOUNTING_HEADER
GO
DROP TABLE ACCOUNTING_APPLICATION
GO
DROP TABLE ACCOUNTING_TRAN_CODE
GO



CREATE TABLE ACCOUNTING_TRAN_CODE (
  DR_CR				VARCHAR(40) NOT NULL,
  CORE_BANKING_TC	VARCHAR(40) NOT NULL,
  STATUS			VARCHAR(10) NOT NULL,
  CREATED_BY		VARCHAR(80) NOT NULL,
  CREATED_DATE		DATETIME DEFAULT GETDATE(),
  MODIFIED_BY		VARCHAR(80) NULL,
  MODIFIED_DATE		DATETIME NULL,
  PRIMARY KEY(DR_CR)
);

CREATE TABLE ACCOUNTING_APPLICATION (
  ID				INTEGER  IDENTITY(1,1),
  NAME				VARCHAR(80) NOT NULL,
  STATUS			VARCHAR(10) NOT NULL,
  CREATED_BY		VARCHAR(80) NOT NULL,
  CREATED_DATE		DATETIME DEFAULT GETDATE(),
  MODIFIED_BY		VARCHAR(80) NULL,
  MODIFIED_DATE		DATETIME NULL,
  PRIMARY KEY(ID)
);

CREATE UNIQUE NONCLUSTERED INDEX AK_NAME
ON ACCOUNTING_APPLICATION(NAME);

CREATE TABLE ACCOUNTING_HEADER (
  ID INTEGER NOT NULL IDENTITY(1,1),
  ACCOUNTING_APPLICATION_ID INTEGER  NOT NULL,
  ACCOUNTING_ID VARCHAR(80) NOT NULL,
  DESCRIPTION VARCHAR(120) NOT NULL,
  CHANNEL_ID VARCHAR(40) NOT NULL,
  CORE_BANKING_REF VARCHAR(80) NOT NULL,
  STATUS		VARCHAR(10) NOT NULL,
  CREATED_BY VARCHAR(80) NOT NULL,
  CREATED_DATE DATETIME DEFAULT GETDATE(),
  PRIMARY KEY(ID),
  INDEX ACCOUNTING_HEADER_FKIndex1(ACCOUNTING_APPLICATION_ID),
  FOREIGN KEY(ACCOUNTING_APPLICATION_ID)
    REFERENCES ACCOUNTING_APPLICATION(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE ACCOUNTING_ENTRIES (
  ID INTEGER  NOT NULL IDENTITY(1,1),
  CREATED_BY VARCHAR(80) NOT NULL,
  ACCOUNTING_TRAN_CODE_DR_CR VARCHAR(40) NOT NULL,
  ACCOUNTING_HEADER_ID INTEGER NOT NULL,
  ACCOUNTING_ID VARCHAR(80) NOT NULL,
  ACCT_NO VARCHAR(100) NOT NULL,
  DR_CR VARCHAR(100) NOT NULL,
  AMOUNT VARCHAR(100) NOT NULL,
  CURRENCY VARCHAR(80) NOT NULL,
  NARRATION VARCHAR(300) NOT NULL,
  INCLUDE_IF VARCHAR(300) NOT NULL,
  CREATED_DATE DATETIME DEFAULT GETDATE(),
  REMARK VARCHAR(100) NULL,
  PRIMARY KEY(ID),
  INDEX ACCOUNTING_ENTRIES_FKIndex1(ACCOUNTING_HEADER_ID),
  INDEX ACCOUNTING_ENTRIES_FKIndex2(ACCOUNTING_TRAN_CODE_DR_CR),
  FOREIGN KEY(ACCOUNTING_HEADER_ID)
    REFERENCES ACCOUNTING_HEADER(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(ACCOUNTING_TRAN_CODE_DR_CR)
    REFERENCES ACCOUNTING_TRAN_CODE(DR_CR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

